version: '2'  # if no version is specified then v1 is assumed. Recommend v2 minimum

services:  # containers. same as docker run
  drupal: # a friendly name. this is also DNS name inside network
    image: drupal:9.2.6
    # environment: # Optional, same as -e in docker run
    ports:
        - 8080:80
    volumes: # Optional, same as -v in docker run
        - drupal-modules:/var/www/html/modules \
        - drupal-profiles:/var/www/html/profiles \
        - drupal-sites:/var/www/html/sites \
        - drupal-themes:/var/www/html/themes \
  psql:
    image: postgres:14.0
    environment: # Optional, same as -e in docker run
        POSTGRES_DB: drupal
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
    volumes:
        - psql:/var/lib/postgresql/data:rw

volumes:
    psql:
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes:
        